### PR TITLE
[~] Fix import of Theseus modules

### PR DESCRIPTION
**Pull request by andrewchan29**
Splitting the functionality into separate module files broke the import. This change fixes that

### CODE REVIEW

**Comment by andrewchan29** [comment]
Ah. It's more broken than I thought. The above fixes Theseus not importing, but now it sporadically fails. Eg: `create_profile` can sometimes work or not work. I think it's to do with running through the different curve fitting functions, but I'm not sure what or how ... yet

**Comment by ESeufert** [comment]
Hmm I can't recreate this error

**Comment by ESeufert** [comment]
FYI I fixed the import thing, I'm not getting the problem with `create_profile `

**Comment by ESeufert** [comment]
This should all be fixed now

**Pull request closed without merging**
